### ISSUE TITLE
❌ Segfault in case of command pipe

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#12]
we get this error after inserting this command `cat |`

<img width="871" alt="Screen Shot 2022-10-25 at 8 09 39 PM" src="https://user-images.githubusercontent.com/57199774/197861994-6af67e82-9aa2-4cfe-911e-45806cc2d3ab.png">

**Comment by OussamaBOUIZ** [comment]
This is  a Syntax Error mate.
We shouldn't be handling this, it is NOT specified in the subject
