### ISSUE TITLE
⚠️ Invalid output

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#13]
we get this output when inserting this command `echo "Hello world" > out`

<img width="289" alt="Screen Shot 2022-10-25 at 9 42 10 PM" src="https://user-images.githubusercontent.com/57199774/197878333-d2877d85-5368-4a21-b46c-f91520931a64.png">

**Comment by OussamaBOUIZ** [comment]
I see the problem! The command writes to stdout rather than writing to the specified file

**Comment by OussamaBOUIZ** [comment]
After fixing multiple issues  and testing the command @ibranad provided here.  I found out that for now the application stopped this behavior and functions as wanted
