### ISSUE TITLE
DOUBLE PROMPT AGAIN

### ISSUE THREAD

**Issue by OussamaBOUIZ** [ibranad/Minishell_42#34]
<img width="700" alt="Screen Shot 2022-11-02 at 1 02 03 PM" src="https://user-images.githubusercontent.com/65982891/199484897-0122186e-3d5f-42c0-ac6c-5987baa53fcb.png">

**Comment by issamjmari** [comment]
This problem may be caused by a child process that wasn't executed properly . I advise you to check these functions : fork, execve, wait. . .

**Comment by OussamaBOUIZ** [comment]
This make no sense till now
