### ISSUE TITLE
Exit should be protected from multiple arguments

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#35]
Passing multiple args to exit should result in an error , whereas in Minishell it executes fine

**Minishell :**
<img width="337" alt="Screen Shot 2022-11-02 at 3 42 21 PM" src="https://user-images.githubusercontent.com/57199774/199519662-1cc017b3-03a7-4731-80ba-94024fb02baf.png">

**Bash:**
<img width="363" alt="Screen Shot 2022-11-02 at 3 44 48 PM" src="https://user-images.githubusercontent.com/57199774/199520317-8e872b9f-498d-411b-a43f-05b5557e7969.png">

**Comment by OussamaBOUIZ** [comment]
I'm working on it

**Comment by OussamaBOUIZ** [comment]
Protected Successfully
