### ISSUE TITLE
🚪Exit should not exit in case of error

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#37]
1. **Passing multiple numeric arguments to exit in bash result in an error and the command is not executed**

<img width="374" alt="Screen Shot 2022-11-03 at 4 16 52 PM" src="https://user-images.githubusercontent.com/57199774/199760709-8c225f68-c679-4a78-8fbc-c1df75f40076.png">

2. **In minishell it returns an error but it executes fine**

<img width="432" alt="Screen Shot 2022-11-03 at 4 18 38 PM" src="https://user-images.githubusercontent.com/57199774/199761136-dc6d2fe6-3c2c-4c66-afe1-b94f61abc316.png">

**Comment by OussamaBOUIZ** [comment]
handled
