### ISSUE TITLE
Command args is INCOMPLETE

### ISSUE THREAD

**Issue by OussamaBOUIZ** [ibranad/Minishell_42#4]
The args vector that we pass to the `execve()` syscall, contains the name of the command as well,  as its first element.
For instance:
`ls -la my_dire/`  should have `{"ls", "-la", NULL}` as the arguments vector.
This should be fixed ASAP, so that we test the `Execute()` method.

**Comment by ibranad** [comment]
This issue was fixed , the main cause was during the parsing more specifically when adding the command arguments, the command was skipped during this phase.
