### ISSUE TITLE
Minishell should not exit when dup2 fail

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#56]
Testing minishell for error return in case when dup2 fail, result in an unexpected exit
### Comparison
**Bash :** 
<img width="374" alt="Screen Shot 2022-11-10 at 3 01 01 PM" src="https://user-images.githubusercontent.com/57199774/201111561-bddeb478-afcb-4e3a-b40b-490cf9e9b5f0.png">

**Minishell :** 
<img width="406" alt="Screen Shot 2022-11-10 at 3 03 10 PM" src="https://user-images.githubusercontent.com/57199774/201112042-86bf70e7-119a-44e4-bc65-437f513cf70a.png">

**Comment by OussamaBOUIZ** [comment]
This issue and the printing of error messages result from the same cause, it'll be fixed soon

**Comment by OussamaBOUIZ** [comment]
<img width="432" alt="Screen Shot 2022-11-10 at 5 58 16 PM" src="https://user-images.githubusercontent.com/65982891/201159998-dcb29877-8fa8-4888-8d08-3986bbad23e9.png">
Done!!
