### ISSUE TITLE
Export double free

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#9]
Double free when exporting an environment variable when using echo (not built-in)

**Comment by OussamaBOUIZ** [comment]
Could you please explain more ?!
what does the ECHO have to do with this problem ? Would you please provide an example

**Comment by ibranad** [comment]
When passing this command to the prompt `export=TERM=xterm-256color` the program crashes

**Comment by OussamaBOUIZ** [comment]
This issue is Fixed.
